apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: mongodb
  namespace: roboshop
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: mongodb
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50