apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: mongodb-storageclass-ebs
  namespace: roboshop
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
  # zone: us-east-1a # volume mounting failed due to availability zone of volume and instance
mountOptions:
  - debug
volumeBindingMode: Immediate